[versions]
agp = "8.3.2"
circleimageview = "3.1.0"
exoplayer = "2.19.1"
glide = "4.16.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
lottie = "4.2.0"
lottieVersion = "6.1.0"
material = "1.10.0"
activity = "1.8.0"
constraintlayout = "2.1.4"
media3Ui = "1.3.1"
media3ExoplayerDash = "1.3.1"
navigationFragment = "2.7.7"
readmoretextview = "2.1.0"
recyclerview = "1.3.2"
navigationRuntime = "2.7.7"
shimmer = "0.5.0"
viewpager2 = "1.0.0"
googleGmsGoogleServices = "4.4.1"
firebaseDatabase = "21.0.0"

[libraries]
circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
exoplayer = { module = "com.google.android.exoplayer:exoplayer", version.ref = "exoplayer" }
exoplayer-dash = { module = "com.google.android.exoplayer:exoplayer-dash", version.ref = "exoplayer" }
exoplayer-ui = { module = "com.google.android.exoplayer:exoplayer-ui", version.ref = "exoplayer" }
exoplayer-core = { module = "com.google.android.exoplayer:exoplayer-core", version.ref = "exoplayer" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-v610 = { module = "com.airbnb.android:lottie", version.ref = "lottieVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Ui" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Ui" }
media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3ExoplayerDash" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigationFragment" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigationFragment" }
readmoretextview = { module = "com.borjabravo:readmoretextview", version.ref = "readmoretextview" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime", version.ref = "navigationRuntime" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebaseDatabase" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
googleGmsGoogleServices = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

